#!/usr/bin/env python
import os
import sys
import optparse
import logging


import cfgparse

USAGE = '%prog [options] <dir>'
DESC = ''

def main():
    parser = optparse.OptionParser(usage=USAGE, description=DESC)
    parser.add_option('-v', '--verbose', action='store_true',
        help='Increase verbosity')
    parser.add_option('-d', '--debug', action='store_true',
        help='Turn on debugging messages')


    (opts, args) = parser.parse_args()

    lvl = logging.ERROR
    if opts.debug:
        lvl = logging.DEBUG

    logging.basicConfig(level=lvl)

    logging.debug('Init done')

if __name__ == "__main__":
    main()
